source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in now_playing_cli_gem.gemspec
gemspec

gem 'now_playing_cli_gem'
