source "https://rubygems.org"
gem 'slideshower'

gem 'omniauth-facebook' # Facebook authentication
gem "koala", "~> 1.10.0rc" # Facebook API
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in slideshower.gemspec
gemspec
